// const FETCH_REQUEST = 'FETCH_REQUEST';
// const FETCH_FAILURE = 'FETCH_FAILURE';
// const FETCH_ADS_SUCCESS = 'FETCH_ADS_SUCCESS';
// const FETCH_REGISTER_SUCCESS = 'FETCH_REGISTER_SUCCESS';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';


export const USER_SESSION = 'USER_SESSION';
// export const USER_SESSION_LOGIN = 'USER_SESSION_LOGIN';