export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_FAILURE = 'FETCH_FAILURE';


export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_ADS = 'FETCH_ADS';
export const MSJ_ADS = 'MSJ_ADS';
export const FETCH_RESULTS_CREAT_ADS = 'FETCH_RESULTS_CREAT_ADS';

export const USER_SESSION = 'USER_SESSION';
