export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_FAILURE = 'FETCH_FAILURE';

// const FETCH_REGISTER_SUCCESS = 'FETCH_REGISTER_SUCCESS';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_ADS = 'FETCH_ADS';
export const MSJ_ADS = 'MSJ_ADS';


export const USER_SESSION = 'USER_SESSION';
// export const USER_SESSION_LOGIN = 'USER_SESSION_LOGIN';